version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mini-asm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: secops
      POSTGRES_PASSWORD: secops123
      POSTGRES_DB: mini_asm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: